app/database/models.py
from sqlalchemy import String, Integer, Column
from sqlalchemy.sql.schema import ForeignKey
from sqlalchemy.sql.sqltypes import DateTime
from sqlalchemy.util.langhelpers import hybridproperty

from database.db_session import Base


class QuizQuestions(Base):
    __tablename__ = 'quiz_questions'

    id = Column(Integer, primary_key=True)
    question = Column(String)
    choice_1 = Column(String)
    choice_2 = Column(String)
    choice_3 = Column(String)
    choice_4 = Column(String)
    answer = Column(Integer)

    def to_dict(self):
        return {
            'id': self.id if self.id else '',
            'question': self.question if self.question else '',
            'choice_1': self.choice_1 if self.choice_1 else '',
            'choice_2': self.choice_2 if self.choice_2 else '',
            'choice_3': self.choice_3 if self.choice_3 else '',
            'choice_4': self.choice_4 if self.choice_4 else '',
            'answer': self.answer if self.answer else ''
            }


class Users(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    username = Column(String)


class UserHighscores(Base):
    __tablename__ = 'quiz_highscores'

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey(Users.id))
    score = Column(Integer)
    category= Column(String)
    date_of_score = Column(DateTime)
    message = Column(String)

    @hybridproperty
    def username(self):
        if self.user_id:
            return Users.query.filter_by(id=self.user_id).first().username
    
    def to_dict(self):
        super().__init__(UserHighscores)

        yield('username', self.username if self.username else '')

app/models.py
from sqlalchemy.util.langhelpers import hybridproperty

from app import db


class QuizQuestions(db.Model):
    __tablename__ = 'quiz_questions'

    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.String)
    choice_1 = db.Column(db.String)
    choice_2 = db.Column(db.String)
    choice_3 = db.Column(db.String)
    choice_4 = db.Column(db.String)
    answer = db.Column(db.Integer)

    def to_dict(self):
        return {
            'id': self.id if self.id else '',
            'question': self.question if self.question else '',
            'choice_1': self.choice_1 if self.choice_1 else '',
            'choice_2': self.choice_2 if self.choice_2 else '',
            'choice_3': self.choice_3 if self.choice_3 else '',
            'choice_4': self.choice_4 if self.choice_4 else '',
            'answer': self.answer if self.answer else ''
            }


class Users(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String)


class UserHighscores(db.Model):
    __tablename__ = 'quiz_highscores'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey(Users.id))
    score = db.Column(db.Integer)
    category= db.Column(db.String)
    date_of_score = db.Column(db.DateTime)
    message = db.Column(db.String)

    @hybridproperty
    def username(self):
        if self.user_id:
            return Users.query.filter_by(id=self.user_id).first().username

    def to_dict(self):
        super().__init__(UserHighscores)

        yield('username', self.username if self.username else '')

app/forms.py
from flask import request
from flask_wtf import FlaskForm
from werkzeug.datastructures import CombinedMultiDict, ImmutableMultiDict
from wtforms.fields.simple import TextAreaField
from wtforms.fields.core import IntegerField, StringField
from wtforms.validators import DataRequired, Optional


class BaseForm(FlaskForm):
    method = 'POST'

    def __init__(self, *args, **kwargs):
        if not any([isinstance(arg, ImmutableMultiDict) for arg in args]):
            kwargs.setdefault('formdata', None)

        formdata = kwargs.get('formdata')
        if formdata and request.files:
            kwargs['formdata'] = CombinedMultiDict((formdata, request.files))

        self.css_class = None
        super().__init__(*args, **kwargs)


class SaveHighscoreForm(BaseForm):
    def __init__(self, *args, **kwargs):
        self.css_class = None
        super().__init__(*args, **kwargs)

    username = StringField(label='Username', validators=[DataRequired()])
    message = TextAreaField(label='Message for the developer', validators=[Optional()])

app/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from constants import STATIC_URL_PATH, CONFIG


def register_routes(app):
    from routes import app_blueprint
    app.register_blueprint(app_blueprint)

    from api.api import api_blueprint
    app.register_blueprint(api_blueprint)


app = Flask(__name__, static_url_path=STATIC_URL_PATH)
app.config.from_object(CONFIG)
print('App config: ', app.config)

db = SQLAlchemy(app)

with app.app_context():
    import models
    register_routes(app)

app/routes.py
from flask import render_template, redirect, request, Blueprint, url_for, flash
from datetime import datetime

from constants import OPEN_TRIVIA_URL, categories
from forms import SaveHighscoreForm
from app import db
from models import UserHighscores, Users
from utils import fetch_api_data, parse_and_save_questions, get_user_highscores


app_blueprint = Blueprint('index', __name__)


@app_blueprint.route('/', methods=['GET'])
def index():
    return render_template('index.html')


@app_blueprint.route('/play-quiz/<cat_num>', methods=['GET'])
def play_quiz(cat_num):
    if cat_num:
        category = categories[cat_num]
        resp = fetch_api_data(OPEN_TRIVIA_URL % cat_num)
        if resp:
            parse_and_save_questions(resp)

            return render_template('quiz.html', question={}, category=category)
    return redirect('/')


@app_blueprint.route('/highscores', methods=['GET', 'POST'])
def highscores():
    scores = get_user_highscores()
    if scores:
        return render_template('highscores.html', scores=scores)
    return redirect('/')


@app_blueprint.route('/save-score', methods=['POST', 'GET'])
def save_score():
    if request.method == 'GET':
        return redirect(url_for('index.highscores'))

    if request.method == "POST":
        score_data = request.get_json()

        username = score_data['username']
        if username:
            user = Users.query.filter_by(username=username).first()

            if not user:
                user = Users(username=username)
                db.session.add(user)
                db.session.commit()

            user_id = user.id

            new_score = UserHighscores(
                user_id=user_id,
                message=score_data['message'],
                score=score_data['score'],
                category=score_data['category'],
                date_of_score=datetime.now()
            )

            db.session.add(new_score)
            db.session.commit()

            return redirect(url_for('index.highscores'))


@app_blueprint.route('/quiz-results', methods=['GET', 'POST'])
def quiz_results():
    if request.method == 'GET':
        return render_template('results.html', scores=get_user_highscores(), form=SaveHighscoreForm())

    if request.method == 'POST':
        score_form = SaveHighscoreForm(formdata=request.form)

        if score_form.validate():
            flash('Score saved successfully!', 'success')
            return redirect(url_for('index.save_score'))
        else:
            flash(score_form.errors, 'danger')

    return redirect(request.referrer)

app/templates/base-form.html
<form novalidate 
    {% if form.target %} target="{{ form.target }}" {% endif %} 
    enctype="multipart/form-data" 
    method="{{ form.method }}"
    action="{{ form.url if form.url else request.url }}">
    
    {{ form.hidden_tag() }}
    {% for field in form if field.widget.input_type not in ('hidden', 'submit') and not field.widget.hide %}
        <div class="form-group">
            {{ field.label }}
            <div class="mb-3">
                {% if field.widget.input_type == 'checkbox' %}
                    <label>{{ field(class='form-check-input', tabindex=1) }}</label>
                {% elif field.widget.input_type == 'file' %}
                    {{ field(tabindex=1) }}
                {% elif field.widget.input_type == 'radio' %}
                    {% for rad in field %}
                        <div class="radio">
                            <label>
                                {{ rad }}
                                {{ rad.label.text }}
                            </label>
                        </div>
                    {% endfor %}
                {% else %}
                    {{ field(class='form-control', tabindex=1) }}
                {% endif %}

                {% if field.description %}
                    <small class="help-inline" >{{ field.description|safe }}</small>
                {% endif %}

                {% if field.errors %}
                    <small class="help-inline" >{{ field.errors[0] }}</small>
                {% endif %}
            </div>    
        </div>
    {% endfor %}

    {% if form.enabled|default(True) %}
        <div class="form-actions text-center">
            <button type="submit" class="{{ css_class if css_class else 'btn btn-primary col-10 mt-2'}}" onclick="onSaveScore()">Submit</button>
        </div>
    {% endif %}
</form>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Fliq</title>

		<!-- CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
			  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/quiz.css') }}">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/results.css') }}">
		
    </head>
    <body>
		
		<div class="" id="app">
			{% include "navbar.html" with context %}
			<div class="container-center scrollbar-default">
				{% block content %}{% endblock %}
			</div>
        </div>

		<!-- JS -->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
				integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/vendor/jquery-3.6.0.min.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/vendor/underscore-udm-min.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/vendor/backbone-min.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
    </body>
</html>

app/templates/highscores.html
{% extends "base.html" %}
{% block content %}
<div class="container-center">
	<div class="col-md-3 w-50">
		<div class="row text-center">
			<h3 class="main-title">Highscores</h3>
		</div>
		<div class="row">
			<ol class="list-group list-group-numbered">
				{% for score in scores %}
					<li class="list-group-item d-flex justify-content-between align-items-start">
						<div class="ms-2 me-auto">
							<div class="fw-bold">{{ score.username }}</div>
							{{ score.category }}
						</div>
						<span id="score-tag" class="badge bg-primary rounded-pill">{{ score.score }}</span>
					</li>
				{% endfor %}
			</ol>
		</div>
		<div class="row flex-column flex-center">
			<a id="home-page-btn" class="btn btn-primary" href="/">Home page</a>
		</div>
	</div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="">
	<div class="flex-center flex-column">
		<h1 id="" class="main-title text-center">
			Fliq Quiz
		</h1>
		<div id="main-content" class="text-center">
			Welcome to the web app where you're being quizzed!
			To start, choose a category and press Play.
		</div>
		<select id="category-select" class="form-select" aria-label="Choose a category">
			<option selected value="9">General knowledge</option>
			<option value="17">Science and nature</option>
			<option value="20">Mythology</option>
			<option value="21">Sports</option>
			<option value="22">Geography</option>
			<option value="23">History</option>
			<option value="25">Art</option>
			<option value="27">Animals</option>
		</select>
		<div id="btn-group" class="">
			<a id="play-btn" class="btn btn-primary" href="{{ url_for('index.play_quiz', cat_num=9) }}">Play</a>
			<a class="btn btn-info" href="{{ url_for('index.highscores') }}">Highscores</a>
		</div>
	</div>
</div>
<script src="{{ url_for('static', filename='js/index.js') }}" type="text/javascript"></script>
{% endblock %}

app/templates/navbar.html
{% block content %}
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="collapse navbar-collapse justify-content-md-center" id="navbarNav">
                <ul id="main-menu" class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li id="main-menu-highscores" class="nav-item dropdown">
                        <a id="highscoreDropdownLink" class="nav-link dropdown-toggle" href="{{ url_for('index.highscores') }}"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Highscores
                        </a>
                        <ol id="highscores-list" class="dropdown-menu dropdown-menu-dark list-group-numbered"
                            aria-labelledby="highscoreDropdownLink">
                        </ol>
                    </li>
                    <!--
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/">API</a>
                        </li>
                    -->
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

app/templates/quiz.html
{% extends "base.html" %}

{% block content %}
	<div id="game" class="flex-center flex-column">
		<div id="dashboard" class="row">
			<div id="dashboard-text" class="row">
				<div id="category-div" class="col-sm-4">
					<div class="card">
						<div class="card-body">
							<h5 class="card-title">Category: </h5>
							<p id="category-text" class="card-text">{{ category }}</p>
						</div>
					</div>
				</div>
				<div id="question-div" class="col-sm-4">
					<div class="card">
						<div class="card-body">
							<h5 class="card-title">Question: </h5>
							<p id="question-number" class="card-text"></p>
						</div>
					</div>
				</div>
				<div id="score-div" class="col-sm-4">
					<div class="card">
						<div class="card-body">
							<h5 class="card-title">Score: </h5>
							<p id="score-text" class="card-text">0</p>
						</div>
					</div>
				</div>
			</div>
			<div id="progress-bar-div" class="progress row">
				<div id="progress-bar" class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 0%" 
				aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
			</div>
		</div>
		<h2 id="question">{{ question.question|e }}</h2>
		<div class="choice-container hoverable">
			<p class="choice-prefix">A</p>
			<p class="choice-text" data-number="1">{{ question.choice_1|e }}</p>
		</div>
		<div class="choice-container hoverable">
			<p class="choice-prefix">B</p>
			<p class="choice-text" data-number="2">{{ question.choice_2|e }}</p>
		</div>
		<div class="choice-container hoverable">
			<p class="choice-prefix">C</p>
			<p class="choice-text" data-number="3">{{ question.choice_3|e }}</p>
		</div>
		<div class="choice-container hoverable">
			<p class="choice-prefix">D</p>
			<p class="choice-text" data-number="4">{{ question.choice_4|e }}</p>
		</div>
	</div>

<script src="{{ url_for('static', filename='js/quiz.js') }}" type="text/javascript"></script>
{% endblock %}

app/templates/results.html
{% extends "base.html" %}
{% block content %}
<div id="results-main" class="container-center">
	<div class="col-md-6 flex-center flex-column">
		<h1 id="category-result-text" class="display-6 text-muted text-center"></h1>
		<h1 id="final-score-text">0</h1>

		{% with form=form %}
			{% include 'base-form.html'with context %}
		{% endwith %}
	
	</div>

	<div class="col-md-6">
		<div class="row text-center">
			<h3 class="main-title">Highscores</h3>
		</div>
		<div class="row">
			{% if scores %}
				<ol class="list-group list-group-numbered">
					{% for score in scores %}
						<li class="list-group-item d-flex justify-content-between align-items-start">
							<div class="ms-2 me-auto">
								<div class="fw-bold">{{ score.username }}</div>
								{{ score.category }}
							</div>
							<span id="score-tag" class="badge bg-primary rounded-pill">{{ score.score }}</span>
						</li>
					{% endfor %}
				</ol>
			{% endif %}
		</div>
	</div>
</div>

<script src="{{ url_for('static', filename='js/results.js') }}" type="text/javascript"></script>
{% endblock %}